### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by glenjofe** [det/segmented_tree_seq#1]
**Namespaces**
If you can, instead of `segmented_tree_seq_detail` within `boost`, I'd go with `boost::segmented_tree` for the namespace of your library. The detail namespace within would be `boost::segmented_tree::detail`.

`<boost/segmented_tree/segmented_tree_seq.hpp>` would provide class template `boost::segmented_tree::segmented_tree_seq`. 

You can additionally provide `<boost/segmented_tree_seq.hpp>` which just has:

```
#include <boost/segmented_tree/segmented_tree_seq.hpp>
namespace boost {
   using segmented_tree::segmented_tree_seq;
}
```

To allow convenient usage as `boost::segmented_tree_seq`.

**Branching based on compile-time traits**
Instead of the `if (!is_trivial())` statements, any opposition to expressing that via tag dispatch or SFINAE?  

**Tuple**
If a dependency on empty-base-optimized `std::tuple` implementations was desired, be aware that some implementations may not meet expectations (MSVC).

**Placement new on node types**
The node type does not have to be POD or trivially-default-constructible if a C++11 allocator provides a `void_pointer` type that violates that. 

**Const reference parameters**
For some of the operators, like `operator<`, which currently take non-const reference parameters.

**Comment by det** [comment]
All the suggestions here have been implemented.  Thanks for the feedback Glen.

**Comment by glenfe** [comment]
**Trivial types**
Instead of:

```
struct size_pair_t : allocator_type {
    size_type sz = 0;
    size_pair_t() : allocator_type{} {}
    size_pair_t(const allocator_type& alloc) : allocator_type{alloc}, sz{} { }
} size_pair;
```

Maybe:

```
struct size_pair_t : allocator_type {
    size_type sz;
    size_pair_t() = default;
    size_pair_t(const allocator_type& alloc) : allocator_type{alloc}, sz{} { }
} size_pair = size_pair_t{};
```

So that the type has potential to be trivial.

**Comment by glenfe** [comment]
**Placement new**
For placement new, perhaps `::new(static_cast<void*>(p))` instead of `new(p)` (i.e. global scope, and `void*` overload).

**Comment by det** [comment]
Implemented potentially trivial pairs and global placement new, Thanks.

**Comment by glenfe** [comment]
**std::allocator specialization**
One potential issue about the specialization for when the allocator type is `std::allocator<T>` is that the standard allows std::allocator to be specialized for user-defined types and, if so, the user might have provided `construct` and `destroy` in that specialization.
